#!/bin/sh


  ############
### Settings ###
  ############

mod="Mod4"
alt="Mod1"
riverctl spawn "dbus-update-activation-environment SEATD_SOCK DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river SDL_VIDEODRIVER=wayland"

## Color
riverctl background-color 0x946a90
riverctl background-color-focused 0x1e9c8f
riverctl background-color-unfocused 0x040a0a
# 0xbbbbbb
# 0x946a90
# 0x222222

## Keyboard repeat rate?
riverctl set-repeat 50 300


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ###########
### Startup ###
  ###########

# swaybg
riverctl spawn "swaybg -m fill -i ~/Pictures/wallpapers/chito-yuu-snow-walk.jpg"

# wlsunset
riverctl spawn "killall wlsunset"
riverctl spawn "wlsunset"

# waybar
riverctl spawn "killall waybar"
riverctl spawn "waybar -c $HOME/.config/waybar/config -s $HOME/.config/waybar/style.css"




#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ##########
### System ###
  ##########

# Exit river
riverctl map normal $mod+Shift Q exit

# Reload config
riverctl map normal $mod+Shift R spawn "~/.config/river/init"

# bemenu
riverctl map normal $mod P spawn bemenu-run

# lock
#riverctl map normal $mod+Control L spawn "swaylock" 

# shutdown
#riverctl map normal $alt+Shift


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ###########
### Windows ###
  ###########

# Close current window
riverctl map normal $mod+Shift C close

# Spawn Terminal
riverctl map normal $mod Return spawn foot


# next/previous window in the layout stack
riverctl map normal $mod K focus-view next
riverctl map normal $mod J focus-view previous

# next/previous window SWAP in the layout stack
riverctl map normal $mod+Shift K swap next
riverctl map normal $mod+Shift J swap previous

# ratio decrease/increase increments
riverctl map normal $mod+Shift L send-layout-cmd rivertile "main-ratio +.05"
riverctl map normal $mod+Shift H send-layout-cmd rivertile "main-ratio -.05"


# Bump to focused view
riverctl map normal $mod+Shift Return zoom

# count decrement/increment in master-stack.
#riverctl map normal $mod-Shift # send-layout-cmd rivertile "main-count +1"
#riverctl map normal $mod-Shift # send-layout-cmd rivertile "main-count -1"


# ? Output? next/previous focus-output?
# ? Output? next/previous send-to-output?




#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  #####################
### Floating controls ###
  #####################

# change all to $mod, $alt, and (maybe) $ctrl

# floating mode
riverctl map normal $mod Space toggle-float

# Super+Alt+{H,J,K,L} to move views
#riverctl map normal Super+Alt H move left 100
#riverctl map normal Super+Alt J move down 100
#riverctl map normal Super+Alt K move up 100
#riverctl map normal Super+Alt L move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
#riverctl map normal Super+Alt+Control H snap left
#riverctl map normal Super+Alt+Control J snap down
#riverctl map normal Super+Alt+Control K snap up
#riverctl map normal Super+Alt+Control L snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
#riverctl map normal Super+Alt+Shift H resize horizontal -100
#riverctl map normal Super+Alt+Shift J resize vertical 100
#riverctl map normal Super+Alt+Shift K resize vertical -100
#riverctl map normal Super+Alt+Shift L resize horizontal 100

# Left Mouse drag to move floating windows
riverctl map-pointer normal $mod BTN_LEFT move-view

# Left Mouse drag to resize floating windows
riverctl map-pointer normal $mod BTN_RIGHT resize-view





#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ################
### Window Modes ###
  ################

# Fullscreen
riverctl map normal $mod F toggle-fullscreen


## Layout Orientation
riverctl map normal $mod Up send-layout-cmd rivertile "main-location top"
riverctl map normal $mod Up send-layout-cmd rivertile "main-location right"
riverctl map normal $mod Up send-layout-cmd rivertile "main-location bottom"
riverctl map normal $mod Up send-layout-cmd rivertile "main-location left"





#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ##################
### Tags and Focus ###
  ##################

# next tag
riverctl map normal $mod L spawn "cycle-focused-tags next 9"
riverctl map normal $mod H spawn "cycle-focused-tags previous 9"

for i in $(seq 1 9)
do
	tags=$((1 << ($i - 1)))

	# change focused tag [0-8]
	riverctl map normal $mod $i set-focused-tags $tags

	# move to another tag (tag the focused window with tag [0-8])
	riverctl map normal $mod+Shift $i set-view-tags $tags

	# view windows of another workspace (add tag [0-8] into current focus)
	riverctl map normal $mod+Control $i toggle-focused-tags $tags

	# toggle tag [0-8] of focused view
	riverctl map normal $mod+Shift+Control $i toggle-view-tags $tags
done

# focus all tags
# tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal $mod 0 set-focused-tags $all_tags
riverctl map normal $mod+Shift 0 set-view-tags $all_tags


# View all tags
# Tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal $mod \` set-focused-tags $all_tags
riverctl map normal $mod+Shift \` set-view-tags $all_tags





#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ###########
### Special ###
  ###########

## Media Keys

for mode in normal locked
do
	# Audio
	riverctl map $mode None XF86AudioRaiseVolume spawn 'pactl set-sink-volume @DEFAULT_SINK@ +5%'
	riverctl map $mode None XF86AudioLowerVolume spawn 'pactl set-sink-volume @DEFAULT_SINK@ -5%'
	riverctl map $mode None XF86AudioMute		 spawn 'pactl set-sink-mute @DEFAULT_SINK@ toggle'
	# Brightness
	riverctl map $mode None XF86MonBrightnessUp   spawn 'light -A 5'
	riverctl map $mode None XF86MonBrightnessDown spawn 'light -U 5'
	# Media
    #riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    #riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    #riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    #riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

done



#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ####################
### Passthrough mode ###
  ####################

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
#riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
#riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
#riverctl map passthrough Super F11 enter-mode normal



#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ########
### Misc ###
  ########



#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ################
### Applications ###
  ################

## Start floating
#riverctl float-filter-add app-id float
#riverctl float-filter-add title "popup title with spaces"

## Decorations
# Set app-ids and titles of views which should use client side decorations
#riverctl csd-filter-add app-id "gedit"





## Default layout generator
##### MOVED TO THE BOTTOM
riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6

